{{if .Values.tap.certManager.issuerSecretName -}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: {{ .Values.namespace }}
spec:
  ca:
    secretName: {{ .Values.tap.certManager.issuerSecretName }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  namespace: {{ .Values.namespace }}
spec:
  secretName: tap-k8s-tls
  duration: {{ .Values.tap.certManager.duration }}
  renewBefore: {{ .Values.tap.certManager.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap-injector
  namespace: {{ .Values.namespace }}
spec:
  secretName: tap-injector-k8s-tls
  duration: {{ .Values.tapInjector.certManager.duration }}
  renewBefore: {{ .Values.tapInjector.certManager.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap-injector.linkerd-viz.svc
  dnsNames:
  - tap-injector.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
{{ end -}}