{{- if not .Values.autoscaling.enabled }}
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "github-actions-runners.fullname" . }}
  labels:
    {{- include "github-actions-runners.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "github-actions-runners.fullname" . }}
  {{- with .Values.autoscaling.scaleUpTriggers }}
  scaleUpTriggers:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
