{{- range .Values.runnerDeployments }}
---
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
{{- $autoscaling := .autoscaling | default dict }}
{{- $autoscalingEnabled := $autoscaling.enabled | default false }}
{{- $minReplicas := $autoscaling.minReplicas | default $.Values.global.autoscaling.minReplicas }}
{{- $maxReplicas := $autoscaling.maxReplicas | default $.Values.global.autoscaling.maxReplicas }}
{{- $scaleUpTriggers := $autoscaling.scaleUpTriggers | default $.Values.global.autoscaling.scaleUpTriggers }}
{{- $metrics := $autoscaling.metrics | default $.Values.global.autoscaling.metrics }}
{{- if $autoscalingEnabled }}
kind: HorizontalRunnerAutoscaler
apiVersion: actions.summerwind.dev/v1alpha1
metadata:
  name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  labels:
    github-actions-runner: {{ .name }}
    {{- include "github-actions-runners.labels" $ | nindent 4 }}
spec:
  minReplicas: {{ $minReplicas }}
  maxReplicas: {{ $maxReplicas }}
  scaleTargetRef:
    name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  {{- with $scaleUpTriggers }}
  scaleUpTriggers:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $metrics }}
  metrics:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
