{{- range .Values.runnerDeployments }}
---
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
{{- if .autoscaling.enabled }}
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  labels:
    github-actions-runner: {{ .name }}
    {{- include "github-actions-runners.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  {{- with .autoscaling.scaleUpTriggers }}
  scaleUpTriggers:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
