{{- range .Values.runnerDeployments }}
---
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
{{- $imageSpec := .image | default dict }}
{{- $repository := $imageSpec.repository | default $.Values.global.image.repository }}
{{- $tag := $imageSpec.tag | default $.Values.global.image.tag }}
{{- $pullPolicy := $imageSpec.pullPolicy | default $.Values.global.image.pullPolicy }}
kind: RunnerDeployment
apiVersion: actions.summerwind.dev/v1alpha1
metadata:
  name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  labels:
    github-actions-runner: {{ .name }}
    {{- include "github-actions-runners.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount | default $.Values.global.replicaCount }}
  template:
    metadata:
      {{- with (default $.Values.global.podAnnotations .podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        github-actions-runner: {{ .name }}
        {{- include "github-actions-runners.selectorLabels" $ | nindent 8 }}
    spec:
      serviceAccountName: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
      image: {{ printf "%s:%s" $repository $tag }}
      imagePullPolicy: {{ $pullPolicy }}
      {{- if .config.githubRepository }}
      repository: "{{ .config.githubRepository }}"
      {{- end }}
      {{- if .config.githubOrganization }}
      organization: "{{ .config.githubOrganization }}"
      {{- end }}
      {{- with (default $.Values.global.config.labels .config.labels )}}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ephemeral: {{ .config.ephemeral | default $.Values.global.config.ephemeral }}
      dockerEnabled: {{ .config.dockerEnabled | default $.Values.global.config.dockerEnabled }}
      dockerMTU: {{ .config.dockerMTU | default $.Values.global.config.dockerMTU }}
      dockerRegistryMirror: "{{ .config.dockerRegistryMirror | default $.Values.global.config.dockerRegistryMirror }}"
      dockerdWithinRunnerContainer: {{ .config.dockerdWithinRunnerContainer | default $.Values.global.config.dockerdWithinRunnerContainer }}
      securityContext:
        {{- toYaml (default $.Values.global.securityContext .securityContext )| nindent 8 }}
      {{- with (default $.Values.global.nodeSelector .nodeSelector )}}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $.Values.global.affinity .affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default $.Values.global.tolerations .tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      resources:
        {{- toYaml (default $.Values.global.resources .resources) | nindent 8 }}
      {{- with (default $.Values.global.env .env) }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
