{{- range .Values.runnerDeployments }}
{{- $enabled := printf "%t" .enabled }}
{{- if regexMatch "nil" $enabled }}{{- $enabled = "true" }}{{- end }}
{{- if (eq $enabled "true") }}
{{- $serviceAccount := .serviceAccount | default dict }}
{{- $create := $serviceAccount.create | default $.Values.global.serviceAccount.create }}
{{- $annotations := $serviceAccount.annotations | default $.Values.global.serviceAccount.annotations }}
{{- if $create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-actions-runners.fullname" $ }}-{{ .name }}
  labels:
    github-actions-runner: {{ .name }}
    {{- include "github-actions-runners.labels" $ | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
