{{- if .Values.linkerd.enabled -}}
{{- if and .Values.linkerd.trustAnchor.ca.crt .Values.linkerd.trustAnchor.ca.key -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-trust-anchor
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
data:
  tls.crt: {{ b64enc (.Values.linkerd.trustAnchor.ca.crt | trim )}}
  tls.key: {{ b64enc (.Values.linkerd.trustAnchor.ca.key | trim )}}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  secretName: linkerd-identity-issuer
  duration: {{ .Values.linkerd.identityIssuer.duration }}
  renewBefore: {{ .Values.linkerd.identityIssuer.renewBefore }}
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.{{ .Values.linkerd.namespace }}.cluster.local
  dnsNames:
  - identity.{{ .Values.linkerd.namespace }}.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
{{- if and .Values.linkerd.webhook.ca.crt .Values.linkerd.webhook.ca.key -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: webhook-issuer-tls
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
data:
  tls.crt: {{ b64enc (.Values.linkerd.webhook.ca.crt | trim )}}
  tls.key: {{ b64enc (.Values.linkerd.webhook.ca.key | trim )}}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: webhook
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: policy-validator
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: {{ .Values.linkerd.webhook.issuer.duration }}
  renewBefore: {{ .Values.linkerd.webhook.issuer.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-policy-validator.{{ .Values.linkerd.namespace }}.svc
  dnsNames:
  - linkerd-policy-validator.{{ .Values.linkerd.namespace }}.svc
  - linkerd-policy-validator.{{ .Values.linkerd.namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: {{ .Values.linkerd.webhook.issuer.duration }}
  renewBefore: {{ .Values.linkerd.webhook.issuer.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.{{ .Values.linkerd.namespace }}.svc
  dnsNames:
  - linkerd-proxy-injector.{{ .Values.linkerd.namespace }}.svc
  - linkerd-proxy-injector.{{ .Values.linkerd.namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: {{ .Values.linkerd.namespace }}
  labels:
    linkerd.io/control-plane-component: sp-validator
    linkerd.io/control-plane-ns: {{ .Values.linkerd.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: {{ .Values.linkerd.webhook.issuer.duration }}
  renewBefore: {{ .Values.linkerd.webhook.issuer.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.{{ .Values.linkerd.namespace }}.svc
  dnsNames:
  - linkerd-sp-validator.{{ .Values.linkerd.namespace }}.svc
  - linkerd-sp-validator.{{ .Values.linkerd.namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
{{- end }}
