{{- if .Values.linkerdJaeger.enabled -}}
{{- if and .Values.linkerdJaeger.webhook.ca.crt .Values.linkerdJaeger.webhook.ca.key -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: webhook-issuer-tls
  namespace: {{ .Values.linkerdJaeger.namespace }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/jaeger: {{ .Values.linkerdJaeger.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
data:
  tls.crt: {{ b64enc (.Values.linkerdJaeger.webhook.ca.crt | trim )}}
  tls.key: {{ b64enc (.Values.linkerdJaeger.webhook.ca.key | trim )}}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: {{ .Values.linkerdJaeger.namespace }}
  labels:
    linkerd.io/control-plane-component: webhook
    linkerd.io/jaeger-ns: {{ .Values.linkerdJaeger.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-injector
  namespace: {{ .Values.linkerdJaeger.namespace }}
  labels:
    linkerd.io/control-plane-component: webhook
    linkerd.io/jaeger-ns: {{ .Values.linkerdJaeger.namespace }}
    {{- include "linkerd-helpers.labels" . | nindent 4 }}
spec:
  secretName: jaeger-injector-k8s-tls
  duration: {{ .Values.linkerdJaeger.webhook.issuer.duration }}
  renewBefore: {{ .Values.linkerdJaeger.webhook.issuer.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: jaeger-injector.{{ .Values.linkerdJaeger.namespace }}.svc
  dnsNames:
  - jaeger-injector.{{ .Values.linkerdJaeger.namespace }}.svc
  - jaeger-injector.{{ .Values.linkerdJaeger.namespace }}.svc.cluster.local
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
{{- end }}
