{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "node-local-dns.fullname" . }}
{{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
{{- end }}
  labels:
    {{- include "node-local-dns.labels" . | nindent 4 }}
spec:
  groups:
  - name: nodelocaldns.rules
    rules:
    - alert: NodeLocalDNSSetupErrorsHigh
      annotations:
        description: "There are {{`{{`}} $labels.errortype {{`}}`}} errors setting up Node Local DNS."
      expr: |
        rate(coredns_nodecache_setup_errors{job="node-local-dns"}[5m]) > 0
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSSetupErrorsHighNew
      annotations:
        description: "There are {{`{{`}} $labels.errortype {{`}}`}} errors setting up Node Local DNS."
      expr: |
        rate(coredns_nodecache_setup_errors_total{job="node-local-dns"}[5m]) > 0
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: "NodeLocalDNSDown"
      annotations:
        description: "NodeLocalDNS has disappeared from Prometheus target discovery."
      expr: |
        absent(up{job="node-local-dns"} == 1)
      for: 15m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSLatencyHigh
      annotations:
        description: "NodeLocalDNS has 99th percentile latency of {{`{{`}} $value {{`}}`}} seconds for server {{`{{`}} $labels.server {{`}}`}} zone {{`{{`}} $labels.zone {{`}}`}} ."
      expr: |
        histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job="node-local-dns"}[5m])) by(server, zone, le)) > 4
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSErrorsHigh
      annotations:
        description: "NodeLocalDNS is returning SERVFAIL for {{`{{`}} $value | humanizePercentage {{`}}`}} of requests."
      expr: |
        sum(rate(coredns_dns_responses_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_dns_responses_total{job="node-local-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSErrorsHigh
      annotations:
        description: "NodeLocalDNS is returning SERVFAIL for {{`{{`}} $value | humanizePercentage {{`}}`}} of requests."
      expr: |
        sum(rate(coredns_dns_responses_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_dns_responses_total{job="node-local-dns"}[5m])) > 0.01
      for: 10m
      labels:
        severity: warning
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
  - name: nodelocaldns-forward.rules
    rules:
    - alert: NodeLocalDNSForwardLatencyHigh
      annotations:
        description: "NodeLocalDNS has 99th percentile latency of {{`{{`}} $value {{`}}`}} seconds forwarding requests to {{`{{`}} $labels.to {{`}}`}}."
      expr: |
        histogram_quantile(0.99, sum(rate(coredns_forward_request_duration_seconds_bucket{job="node-local-dns"}[5m])) by(to, le)) > 4
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSForwardErrorsHigh
      annotations:
        description: "NodeLocalDNS is returning SERVFAIL for {{`{{`}} $value | humanizePercentage {{`}}`}} of forward requests to {{`{{`}} $labels.to {{`}}`}}."
      expr: |
        sum(rate(coredns_forward_responses_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_forward_responses_total{job="node-local-dns"}[5m])) > 0.03
      for: 10m
      labels:
        severity: critical
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSForwardErrorsHigh
      annotations:
        description: "NodeLocalDNS is returning SERVFAIL for {{`{{`}} $value | humanizePercentage {{`}}`}} of forward requests to {{`{{`}} $labels.to {{`}}`}}."
      expr: |
        sum(rate(coredns_forward_responses_total{job="node-local-dns",rcode="SERVFAIL"}[5m]))
          /
        sum(rate(coredns_forward_responses_total{job="node-local-dns"}[5m])) > 0.01
      for: 10m
      labels:
        severity: warning
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSForwardHealthcheckFailureCount
      annotations:
        description: "NodeLocalDNS health checks have failed to upstream server {{`{{`}} $labels.to {{`}}`}}."
      expr: |
        sum(rate(coredns_forward_healthcheck_failures_total{job="node-local-dns"}[5m])) by (to) > 0
      for: 10m
      labels:
        severity: warning
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
    - alert: NodeLocalDNSForwardHealthcheckBrokenCount
      annotations:
        description: "NodeLocalDNS health checks have failed for all upstream servers."
      expr: |
        sum(rate(coredns_forward_healthcheck_broken_total{job="node-local-dns"}[5m])) > 0
      for: 10m
      labels:
        severity: warning
{{- if .Values.prometheusRule.additionalRuleLabels }}
{{ toYaml .Values.prometheusRule.additionalRuleLabels | indent 8 }}
{{- end }}
{{- end }}
