apiVersion: v2
name: prometheus-artifactory-exporter
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v0.8.1
sources:
  - https://github.com/peimanja/artifactory_exporter.git
maintainers:
  - name: Vladimir Syromyatnikov
    email: vladimirs@iguazio.com
