{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.clusterName }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }} 
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "argocd-app-of-apps.labels" $ | nindent 4 }}
spec:
  destination:
    name: {{ $.Values.clusterName }}
    namespace: {{ .namespace }}
  project: {{ $.Values.projectName }}
  source:
    chart: {{ .chart }}
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
{{- if .values }}
    helm:
      values: | {{ nindent 8 (toYaml .values) }}
{{- end }}
  syncPolicy:
    automated:
      prune: {{ $.Values.syncPolicy.prune }}
      selfHeal: {{ $.Values.syncPolicy.selfHeal }}
      allowEmpty: {{ $.Values.syncPolicy.allowEmpty }}
{{- end }}
