{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }} 
    {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "argocd-app-of-apps.labels" $ | nindent 4 }}
spec:
  destination:
    name: {{ $.Values.clusterName }}
    namespace: {{ .namespace }}
  project: {{ $.Values.projectName }}
  source:
    chart: {{ .chart }}
    repoURL: {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
{{- if .values }}
    helm:
      values: |
        {{ .values | nindent 8 }}
{{- end }}
{{- if $.Values.syncPolicy }}
  syncPolicy:
    automated:
      {{- with $.Values.syncPolicy }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
{{- if and $.Values.syncOptions $.Values.syncPolicy }}
    syncOptions:
{{- range $name, $value := $.Values.syncOptions }}
      - {{ $name }}={{ $value }}
{{- end }}
{{- end }}
{{- end }}
