{{- if .Values.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "prometheus-artifactory-exporter.fullname" . }}
  labels:
    {{- include "prometheus-artifactory-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus-artifactory-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-artifactory-exporter.serviceAccountName" . }}
{{- end -}}
