{{- if .Values.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "prometheus-artifactory-exporter.fullname" . }}
  labels:
    {{- include "prometheus-artifactory-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    resourceNames:
    - {{ include "prometheus-artifactory-exporter.fullname" . }}-psp
    verbs:
    - use
{{- end -}}
