{{if .Values.webhook.certManager.enabled -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: webhook-issuer-tls
  namespace: {{ .Values.namespace }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{ .Values.namespace }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
data:
  tls.crt: {{ b64enc (.Values.webhook.certManager.tlsCrt | trim )}}
  tls.key: {{ b64enc (.Values.webhook.certManager.tlsKey | trim )}}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: {{ .Values.namespace }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{ .Values.namespace }}
spec:
  ca:
    secretName: webhook-issuer-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-injector
  namespace: {{ .Values.namespace }}
  labels:
    linkerd.io/extension: jaeger
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  secretName: jaeger-injector-k8s-tls
  duration: {{ .Values.webhook.certManager.duration }}
  renewBefore: {{ .Values.webhook.certManager.renewBefore }}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: jaeger-injector.linkerd.svc
  dnsNames:
  - jaeger-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
{{ end -}}
